name: Node.js CI

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: self-hosted

    steps:
      - uses: actions/setup-node@v1
      - uses: actions/checkout@v2
      - run: npm install
      - run: npm run test
      - run: npm run lint
      - run: npm run build
      - run: FIREBASE_RC=${{ secrets.FIREBASE_RC }} FIREBASE_JSON=${{ secrets.FIREBASE_JSON }} npm run use_secrets
      - run: npm run deploy
